name: $hd_bot

permissions: write-all

on:
  workflow_dispatch:
  repository_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'hd/bot'
    
    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'hd/bot/-'

  notify:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/repository-dispatch@v3
      with:
        repository: hd4ru/space
        event-type: dependency_changed
